require 'Tokenizer'
bob = Tokenizer::Tokenizer.new("(function(){var script=document.createElement('script');script.src='http://mir.aculo.us/dom-monster/dommonster.js?'+Math.floor((+new Date)/(864e5));document.body.appendChild(script);}())")
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
puts bob.next_token().inspect
